name: Swift

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
      with:
        swift-version: "5.2.0"
    - name: Check version
      run: swift --version
    - name: Build
      run: swift build -v
